name: Seattle PD Shorts Bot

on:
  schedule:
    - cron: '0 8,20 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install -U "yt-dlp[default]"
          pip install moviepy==1.0.3 pillow google-api-python-client google-auth-oauthlib
      
      - name: Run bot
        env:
          YT_TOKEN: ${{ secrets.YT_TOKEN }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python bot.py
      
      - name: Commit queue changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Bot"
          git add upload_queue.json links.txt
          git diff --staged --quiet || git commit -m "Update queue"
          git push
        continue-on-error: true
